### ISSUE TITLE
Add alacritty config

### ISSUE THREAD

**Issue by maxbeizer** [maxbeizer/dotfiles#2]
```yaml
colors:
  schemes:
  solarized_dark: &solarized_dark
    primary:
      background: '0x002b36'
      foreground: '0x839496'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

  solarized_light: &solarized_light
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

colors: *solarized_dark

window:
  dynamic_padding: true

scrolling:
  history: 100000

font:
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic
  size: 16.0

mouse:
  url:
    modifiers: Command

selection:
  save_to_clipboard: true
```
